#!/usr/bin/env python3
"""Rewrite the generated catalogue block of README.md from the catalogues.

The counts in "Current catalogue" used to be hand-edited on every refresh and
were the only stale-prone prose on the site. This script regenerates exactly
that block (between the BEGIN/END GENERATED markers) from:

- data/models.json       the sanitised catalogue this site publishes (tier
  counts, unlisted ids, the as-of date)
- reference/models.json  the canonical knowledge base one level up, when
  present (per-Region active ids, used for the `/models` listing breakdown;
  NOT part of this public repo)

Without the canonical file (standalone clone) the `/models` listing line is
skipped rather than guessed; the rest still regenerates.

Usage:
    python3 scripts/sync-readme.py           # rewrite README.md in place
    python3 scripts/sync-readme.py --check   # exit 1 if README.md is stale
"""
from __future__ import annotations

import json
import re
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = REPO / "README.md"
DATA = REPO / "data" / "models.json"
CANON = REPO.parents[1] / "reference" / "models.json"

BEGIN = "<!-- BEGIN GENERATED:catalogue -->"
END = "<!-- END GENERATED -->"
MONTHS = ("January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December")


def month_name(iso: str) -> str:
    y, m, d = (int(p) for p in iso.split("-"))
    return f"{d} {MONTHS[m - 1]} {y}"


def bullet(text: str) -> str:
    """A '- ' bullet wrapped to 76 columns with two-space continuation."""
    return "\n".join(textwrap.wrap(text, width=76, initial_indent="- ",
                                   subsequent_indent="  "))


def build_body() -> str:
    cat = json.loads(DATA.read_text())
    models = cat["models"]
    team = [m for m in models if "team" in m.get("tiers", [])]
    personal = [m for m in models if "personal" in m.get("tiers", [])]
    team_chat = [m for m in team if m["kind"] == "chat"]
    pers_chat = [m for m in personal if m["kind"] == "chat"]
    unlisted = sorted(m["id"] for m in team_chat if m["status"] == "unlisted")

    out = [f"As of {month_name(cat['updated'])}:", ""]
    out.append(bullet(f"Team exposes {len(team_chat)} chat models; Personal "
                      f"exposes {len(pers_chat)} (a strict subset)."))

    if CANON.exists():
        canon = json.loads(CANON.read_text())
        live = [m for m in canon["models"]
                if "team" in m.get("tiers", []) and "global" in m.get("regions", [])
                and m.get("status") == "active" and m["kind"] != "video"]
        kinds: dict[str, int] = {}
        for m in live:
            kinds[m["kind"]] = kinds.get(m["kind"], 0) + 1
        videos = sum(1 for m in canon["models"]
                     if "team" in m.get("tiers", []) and "global" in m.get("regions", [])
                     and m.get("status") == "active" and m["kind"] == "video")
        out.append(bullet(f"`/models` lists {len(live)} ids per Team key: "
                          f"{kinds.get('chat', 0)} chat + {kinds.get('image', 0)} image + "
                          f"{kinds.get('tts', 0)} TTS + {kinds.get('realtime', 0)} "
                          f"realtime audio. The {videos} video models never appear "
                          "on `/models` (async endpoint)."))

    if unlisted:
        name = ", ".join(f"`{m}`" for m in unlisted)
        one = "One additional chat model" if len(unlisted) == 1 else \
            f"{len(unlisted)} additional chat models"
        verb = "is" if len(unlisted) == 1 else "are"
        pron = "it" if len(unlisted) == 1 else "them"
        out.append(bullet(f"{one} ({name}) {verb} servable by exact id but not "
                          f"surfaced on `/models`; the catalogue carries {pron} "
                          "as `unlisted`."))

    out.append(bullet("The exact counts move as models land. "
                      "[`data/models.json`](data/models.json) carries the current "
                      "list and its `updated` date; trust it over this prose."))
    out.append(bullet("This block is generated by `scripts/sync-readme.py` from "
                      "the catalogue; the bullets after it are hand-maintained."))
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    text = README.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(text):
        sys.exit("README.md is missing the generated catalogue markers")
    new = BEGIN + "\n" + build_body() + "\n" + END
    updated = pat.sub(lambda _: new, text, count=1)
    if updated == text:
        return 0
    if check:
        print("README.md catalogue block is stale; run scripts/sync-readme.py",
              file=sys.stderr)
        return 1
    README.write_text(updated)
    print("README.md catalogue block regenerated from data/models.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
